run:
  concurrency: 2
  timeout: 5m
  go: "1.19"

linters:
  disable:
    - containedctx
    - contextcheck
    - paralleltest
    - goimports
  enable:
    - gofmt
    - goconst
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - unparam
    - misspell

linters-settings:
  stylecheck:
    checks:
      - all
      - '-ST1016' # disable the rule ST1016
